/* eslint-disable */

import { writeFile } from 'fs';

const targetPath = './src/environments/environment.ts';

const envConfigFile = `
// This file was autogenerated by dynamically running config.ts and using dotenv for managing firebase secrets

export const environment = {
  production: false,
  firebase: {
      apiKey: '${process.env.FIREBASE_API_KEY}',
      authDomain: '${process.env.FIREBASE_AUTH_DOMAIN}',
      databaseURL: '${process.env.FIREBASE_DB}',
      projectId: '${process.env.FIREBASE_PROJECT_ID}',
      storageBucket: '${process.env.FIREBASE_BUCKET}',
      messagingSenderId: '${process.env.FIREBASE_SENDER}',
      appId: '${process.env.FIREBASE_APP_ID}',
      measurementId: '${process.env.FIREBASE_MEASUREMENT_ID}',
  }
};
`;

writeFile(targetPath, envConfigFile, 'utf8', (err) => {
  if (err) {
    return console.log(err);
  }
});

/* eslint-enable */
